# Generated by Django 2.2 on 2020-08-10 15:50

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDexament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_patient', models.CharField(max_length=40)),
                ('Horodatage_création_de_demande', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Sexe', models.CharField(max_length=10)),
                ('Service', models.CharField(max_length=10)),
                ('Nature_de_prelèvement', models.CharField(max_length=10)),
                ('Médecin_prescripteur', models.CharField(max_length=10)),
                ('Nature_des_tubes', models.CharField(max_length=10)),
                ('Nature_examen', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete='None', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
