# Generated by Django 2.2 on 2020-08-10 15:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemandeDexament',
            new_name='DemandeDexamen',
        ),
    ]
