# Generated by Django 2.2 on 2020-08-10 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_auto_20200810_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedexamen',
            name='Age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
    ]
