# Generated by Django 2.2 on 2020-08-10 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_demandedexamen_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedexamen',
            name='Diagnostic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Nombre_de_tubes',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='demandedexamen',
            name='Age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='demandedexamen',
            name='Médecin_prescripteur',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='demandedexamen',
            name='Nature_de_prelèvement',
            field=models.CharField(choices=[('Sang', 'Sang'), ('Urine', 'Urine'), ('LCR', 'LCR'), ('Liquide_d_acite', 'Liquide_d_acite'), ('Selles', 'Selles'), ('Pus', 'Pus'), ('Hémoculture', 'Hémoculture')], max_length=10),
        ),
        migrations.AlterField(
            model_name='demandedexamen',
            name='Nature_des_tubes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='demandedexamen',
            name='Nature_examen',
            field=models.CharField(choices=[('NONE', 'NONE'), ('Biochimie', 'Biochimie'), ('Hémobiologie', 'Hémobiologie'), ('Parasitologie-Mycologie', 'Parasitologie-Mycologie'), ('Microbiologie', 'Microbiologie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='demandedexamen',
            name='Service',
            field=models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], max_length=10),
        ),
        migrations.AlterField(
            model_name='demandedexamen',
            name='Sexe',
            field=models.CharField(choices=[('Femme', 'Femme'), ('Himme', 'Homme')], max_length=10),
        ),
    ]
