# Generated by Django 2.2 on 2020-09-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0008_biochimieminresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='biochimieminresult',
            name='Médecin',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
