# Generated by Django 2.2 on 2020-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0009_biochimieminresult_médecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilandurgenceresult',
            name='Sexe',
            field=models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='biochimieminresult',
            name='Sexe',
            field=models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='biochimieresult',
            name='Sexe',
            field=models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coproparasitologyresult',
            name='Sexe',
            field=models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='demandedexamen',
            name='Sexe',
            field=models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10),
        ),
    ]
