# Generated by Django 2.2 on 2020-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0011_auto_20200927_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='coproparasitologyresult',
            name='Autres',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='coproparasitologyresult',
            name='Autre',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
