# Generated by Django 2.2 on 2020-09-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0012_auto_20200927_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandedexamen',
            name='Service',
            field=models.CharField(choices=[('Externe', 'Externe'), ('Interne (COA)', 'Interne (COA)'), ('Interne (POA)', 'Interne (POA)'), ('Interne (COB)', 'Interne (COB)'), ('Interne (Curtillet)', 'Interne (Curtillet)'), ('Interne (Chir Plastique)', 'Interne (Chir Plastique)'), ('Interne (Chir Générale)', 'Interne (Chir Générale)'), ('Interne (CCI)', 'Interne (CCI)'), ('Interne (Chrurgie Maxito faciale)', 'Interne (Chrurgie Maxito faciale)'), ('Interne (Rea Med Rhu)', 'Interne (Rea Med Rhu)'), ('Interne (Med Interne)', 'Interne (Med Interne)'), ('Interne (Néonat)', 'Interne (Néonat)'), ('Interne (MTV)', 'Interne (MTV)'), ('Interne (PU T)', 'Interne (PU T)'), ('Interne (PU Chir)', 'Interne (PU Chir)'), ('Interne (PU MI)', 'Interne (PU MI)')], max_length=10),
        ),
    ]
