# Generated by Django 2.2 on 2020-09-28 09:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0014_auto_20200928_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='coproparasitologyresult',
            name='Cas_d_erreur',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'erreur1'), (2, 'erreur2'), (3, 'erreur3'), (4, 'erreur4'), (5, 'erreur5')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
