# Generated by Django 2.2 on 2020-09-28 09:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0015_coproparasitologyresult_cas_d_erreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coproparasitologyresult',
            name='Cas_d_erreur',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, 'pas d_erreur'), (2, 'erreur1'), (3, 'erreur2'), (4, 'erreur3'), (5, 'erreur4'), (6, 'erreur5')], max_length=10),
        ),
    ]
