# Generated by Django 2.2 on 2020-09-28 10:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0016_auto_20200928_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coproparasitologyresult',
            name='Cas_d_erreur',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'None'), (2, 'erreur1'), (3, 'erreur2'), (4, 'erreur3'), (5, 'erreur4'), (6, 'erreur5')], max_length=10),
        ),
    ]
