# Generated by Django 2.2 on 2020-09-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dossierpatient', '0007_auto_20200927_1638'),
        ('analyses', '0017_auto_20200928_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilandurgenceresult',
            name='demande_BU',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analyses.DemandeDexamen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biochimieminresult',
            name='demande_BM',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analyses.DemandeDexamen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biochimieresult',
            name='demande_B',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analyses.DemandeDexamen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coproparasitologyresult',
            name='demande_CP',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analyses.DemandeDexamen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='dossier_patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dossierpatient.DossierPatient'),
            preserve_default=False,
        ),
    ]
