# Generated by Django 2.2 on 2020-09-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0018_auto_20200928_1456'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bilandurgenceresult',
            table='BilanDurgenceResult',
        ),
        migrations.AlterModelTable(
            name='biochimieminresult',
            table='BiochimieMinResult',
        ),
        migrations.AlterModelTable(
            name='biochimieresult',
            table='BiochimieResult',
        ),
        migrations.AlterModelTable(
            name='coproparasitologyresult',
            table='CoproParasitologyResult',
        ),
        migrations.AlterModelTable(
            name='demandedexamen',
            table='DemandeDexamen',
        ),
    ]
