# Generated by Django 2.2 on 2020-10-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0021_biochimieresult_troponine'),
    ]

    operations = [
        migrations.AddField(
            model_name='biochimieresult',
            name='HBA1C',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
    ]
