# Generated by Django 2.2 on 2020-10-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0022_biochimieresult_hba1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biochimieresult',
            name='Aspect_du_sérum',
            field=models.CharField(choices=[('clair', 'clair'), ('hémolysé', 'hémolysé'), ('icterique', 'icterique')], max_length=10),
        ),
    ]
