# Generated by Django 2.2 on 2020-10-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0024_auto_20201002_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilandurgenceresult',
            name='Troponine',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biochimieresult',
            name='Aspect_du_sérum',
            field=models.CharField(max_length=10),
        ),
    ]
