# Generated by Django 2.2 on 2020-10-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0025_auto_20201002_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='coproparasitologyresult',
            name='Fievre',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='coproparasitologyresult',
            name='diabete',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
    ]
