# Generated by Django 2.2 on 2020-10-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0026_auto_20201002_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='Amaigrissement',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='Autre',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='Constipation',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='Diarrhée',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='Douleurs',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='Examen_Complémentaire',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='Fievre',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='Nausées',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='Symptomes',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='Vomissement',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='ballonnement_abdominal',
        ),
        migrations.RemoveField(
            model_name='coproparasitologyresult',
            name='diabete',
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Amaigrissement',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Autre',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Constipation',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Diarrhée',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Douleurs',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Examen_Complémentaire',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Fievre',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Nausées',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Symptomes',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Vomissement',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='ballonnement_abdominal',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='diabete',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
    ]
