# Generated by Django 2.2 on 2020-10-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0027_auto_20201002_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandedexamen',
            name='Nature_des_tubes',
        ),
        migrations.AddField(
            model_name='demandedexamen',
            name='Nature_de_tube',
            field=models.CharField(choices=[('Sec', 'Sec'), ('Citrate', 'Citrate'), ('Heparine', 'Heparine'), ('EDTA', 'EDTA')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
