# Generated by Django 2.2 on 2020-10-02 10:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyses', '0028_auto_20201002_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupageSanguin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_patient', models.CharField(max_length=40)),
                ('Horodatage_création_de_groupage', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Adresse', models.CharField(default=None, max_length=200)),
                ('Groupe', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=10)),
                ('Rh', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=10)),
                ('user', models.ForeignKey(on_delete='None', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupageSanguin',
            },
        ),
        migrations.DeleteModel(
            name='BiochimieMinResult',
        ),
    ]
