# Generated by Django 2.2 on 2020-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0030_acinetobacterresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='acinetobacterresult',
            name='Examen_Directe',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acinetobacterresult',
            name='Nature_de_prelèvement',
            field=models.CharField(choices=[('Sang', 'Sang'), ('Urine', 'Urine'), ('LCR', 'LCR'), ('Liquide_d_acite', 'Liquide_d_acite'), ('Selles', 'Selles'), ('Pus', 'Pus'), ('Hémoculture', 'Hémoculture')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
