# Generated by Django 2.2 on 2020-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0031_auto_20201003_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='acinetobacterresult',
            name='Germe_isolé',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
