# Generated by Django 2.2 on 2020-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0032_acinetobacterresult_germe_isolé'),
    ]

    operations = [
        migrations.AddField(
            model_name='acinetobacterresult',
            name='Observation',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
