# Generated by Django 2.2 on 2020-10-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0033_acinetobacterresult_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acinetobacterresult',
            old_name='Horodatage_création_de_résultat',
            new_name='Horodatage_création_de_resultat',
        ),
        migrations.AlterField(
            model_name='acinetobacterresult',
            name='Observation',
            field=models.CharField(max_length=1000),
        ),
    ]
