# Generated by Django 2.2 on 2020-10-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0037_bacteriologieresult_pseudomonasresult_staphylocoqueresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterobacteriesresult',
            old_name='demande_ACIN',
            new_name='demande_entero',
        ),
        migrations.RenameField(
            model_name='enterocoqueresult',
            old_name='demande_ACIN',
            new_name='demande_Ente',
        ),
        migrations.RenameField(
            model_name='pseudomonasresult',
            old_name='demande_ACIN',
            new_name='demande_Pseu',
        ),
        migrations.RenameField(
            model_name='staphylocoqueresult',
            old_name='demande_ACIN',
            new_name='demande_Staphy',
        ),
        migrations.RemoveField(
            model_name='bacteriologieresult',
            name='demande_ACIN',
        ),
        migrations.AddField(
            model_name='bacteriologieresult',
            name='demande_Bact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analyses.DemandeDexamen'),
            preserve_default=False,
        ),
    ]
