# Generated by Django 2.2 on 2020-10-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0038_auto_20201004_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupagesanguin',
            old_name='Horodatage_création_de_groupage',
            new_name='Horodatage_creation_de_groupage',
        ),
    ]
