# Generated by Django 2.2 on 2020-10-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0039_auto_20201004_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biochimieresult',
            name='Aspect_du_sérum',
            field=models.CharField(choices=[('Clair', 'Clair'), ('Clairr', 'Clairr')], max_length=10),
        ),
    ]
