# Generated by Django 2.2 on 2020-08-09 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dossierpatient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierpatient',
            name='horodatage_création_de_dossier',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
