# Generated by Django 2.2 on 2020-09-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossierpatient', '0003_auto_20200809_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossierpatient',
            old_name='horodatage_création_de_dossier',
            new_name='Horodatage_création_de_dossier',
        ),
        migrations.AlterField(
            model_name='dossierpatient',
            name='sexe',
            field=models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10),
        ),
    ]
