# Generated by Django 2.2 on 2020-09-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossierpatient', '0004_auto_20200916_2138'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dossierpatient',
            table='DossierPatient',
        ),
    ]
