# Generated by Django 2.2 on 2020-09-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossierpatient', '0005_auto_20200927_1629'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dossierpatient',
            table=None,
        ),
    ]
