# Generated by Django 2.2 on 2020-09-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossierpatient', '0006_auto_20200927_1631'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dossierpatient',
            table='DossierPatient',
        ),
    ]
