# Generated by Django 2.2 on 2020-10-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossierpatient', '0007_auto_20200927_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossierpatient',
            old_name='Horodatage_création_de_dossier',
            new_name='Horodatage_creation_de_dossier',
        ),
    ]
