# Generated by Django 2.2 on 2020-10-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossierpatient', '0008_auto_20201004_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierpatient',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
